var h;h||=typeof Module !== 'undefined' ? Module : {};var aa=Object.assign({},h),ba=[],ca="./this.program",da=(a,b)=>{throw b;},ea="object"==typeof window,k="function"==typeof importScripts,fa="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,l="",ha,ia,ja;
if(fa){var fs=require("fs"),ka=require("path");l=k?ka.dirname(l)+"/":__dirname+"/";ha=(a,b)=>{a=la(a)?new URL(a):ka.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};ja=a=>{a=ha(a,!0);a.buffer||(a=new Uint8Array(a));return a};ia=(a,b,c,d=!0)=>{a=la(a)?new URL(a):ka.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,g)=>{e?c(e):b(d?g.buffer:g)})};!h.thisProgram&&1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);process.on("uncaughtException",
a=>{if(!("unwind"===a||a instanceof ma||a.context instanceof ma))throw a;});da=(a,b)=>{process.exitCode=a;throw b;}}else if(ea||k)k?l=self.location.href:"undefined"!=typeof document&&document.currentScript&&(l=document.currentScript.src),l=l.startsWith("blob:")?"":l.substr(0,l.replace(/[?#].*/,"").lastIndexOf("/")+1),ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},k&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);
return new Uint8Array(b.response)}),ia=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var na=h.print||console.log.bind(console),q=h.printErr||console.error.bind(console);Object.assign(h,aa);aa=null;h.arguments&&(ba=h.arguments);h.thisProgram&&(ca=h.thisProgram);h.quit&&(da=h.quit);var u;h.wasmBinary&&(u=h.wasmBinary);"object"!=typeof WebAssembly&&oa("no native wasm support detected");
var pa,v=!1,w,qa,x,ra,sa,y,z,A,B,ta=[],ua=[],va=[],wa=[];function xa(){var a=h.preRun.shift();ta.unshift(a)}var C=0,ya=null,za=null;function oa(a){h.onAbort?.(a);a="Aborted("+a+")";q(a);v=!0;w=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Aa=a=>a.startsWith("data:application/octet-stream;base64,"),la=a=>a.startsWith("file://"),D;D="wgui.wasm";if(!Aa(D)){var Ba=D;D=h.locateFile?h.locateFile(Ba,l):l+Ba}
function Ca(a){if(a==D&&u)return new Uint8Array(u);if(ja)return ja(a);throw"both async and sync fetching of the wasm failed";}function Da(a){if(!u&&(ea||k)){if("function"==typeof fetch&&!la(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw`failed to load wasm binary file at '${a}'`;return b.arrayBuffer()}).catch(()=>Ca(a));if(ia)return new Promise((b,c)=>{ia(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Ca(a))}
function Ea(a,b,c){return Da(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{q(`failed to asynchronously prepare wasm: ${d}`);oa(d)})}function Fa(a,b){var c=D;u||"function"!=typeof WebAssembly.instantiateStreaming||Aa(c)||la(c)||fa||"function"!=typeof fetch?Ea(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){q(`wasm streaming compile failed: ${e}`);q("falling back to ArrayBuffer instantiation");return Ea(c,a,b)}))}var E;
function ma(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ga=a=>{for(;0<a.length;)a.shift()(h)},Ha=h.noExitRuntime||!0,Ia="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,F=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ia)return Ia.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|f:(e&7)<<18|g<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|
e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Ja=a=>0===a%4&&(0!==a%100||0===a%400),Ka=[0,31,60,91,121,152,182,213,244,274,305,335],La=[0,31,59,90,120,151,181,212,243,273,304,334],G=(a,b,c)=>{var d=x;if(!(0<c))return 0;var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var f=a.charCodeAt(g);if(55296<=f&&57343>=f){var m=a.charCodeAt(++g);f=65536+((f&1023)<<10)|m&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=
224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0;return b-e},Va=(a,b)=>{Ma=a;Na=b;if(Oa)if(Pa||=!0,0==a)H=function(){var d=Math.max(0,Qa+b-Ra())|0;setTimeout(Sa,d)};else if(1==a)H=function(){Ta(Sa)};else if(2==a){if("undefined"==typeof Ua)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ua=function(d){c.push(d);k?
(void 0===h.setImmediates&&(h.setImmediates=[]),h.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate","*")}}else Ua=setImmediate;H=function(){Ua(Sa)}}},Ra;Ra=()=>performance.now();
var cb=(a,b,c,d,e)=>{Oa=a;Wa=d;var g=I;Pa=!1;Sa=function(){if(!v)if(0<Xa.length){var f=Xa.shift();f.Uc(f.Pc);if(Ya){var m=Ya,n=0==m%1?m-1:Math.floor(m);Ya=f.Rc?n:(8*m+(n+.5))/9}h.setStatus&&(f=h.statusMessage||"Please wait...",m=Ya,n=Za.Tc,m?m<n?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(f):h.setStatus(""));g<I||setTimeout(Sa,0)}else if(!(g<I))if($a=$a+1|0,1==Ma&&1<Na&&0!=$a%Na)H();else{0==Ma&&(Qa=Ra());if(!(v||h.preMainLoop&&!1===h.preMainLoop())){if(!v)try{if(a(),!Ha)try{w=
f=w,ab(f)}catch(p){bb(p)}}catch(p){bb(p)}h.postMainLoop?.()}g<I||("object"==typeof SDL&&SDL.audio?.Yc?.(),H())}};e||(b&&0<b?Va(0,1E3/b):Va(1,1),H());if(c)throw"unwind";},bb=a=>{a instanceof ma||"unwind"==a||da(1,a)},ab=a=>{w=a;Ha||(h.onExit?.(a),v=!0);da(a,new ma(a))},db=a=>{w=a;ab(a)},Pa=!1,H=null,I=0,Oa=null,Wa=0,Ma=0,Na=0,$a=0,Xa=[];function eb(){H=null;I++}var Za={},Qa,Sa,Ya,fb=!1,gb=!1,hb=[];
function ib(){function a(){gb=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}if(!jb){jb=!0;var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),
b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!gb&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}var kb=!1,lb=void 0,J=void 0;
function mb(){if(!fb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var nb=0;function Ta(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===nb)nb=b+1E3/60;else for(;b+2>=nb;)nb+=1E3/60;setTimeout(a,Math.max(nb-b,0))}}var ob=[];function pb(){var a=h.canvas;ob.forEach(b=>b(a.width,a.height))}
function qb(a,b,c){b&&c?(a.Nc=b,a.Kc=c):(b=a.Nc,c=a.Kc);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*
g)}J?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Ua,jb,tb=a=>{var b=rb();a();sb(b)},ub=0,vb=[];
function wb(){if(navigator.userActivation?navigator.userActivation.isActive:ub&&xb.oc)for(var a=0;a<vb.length;++a){var b=vb[a];vb.splice(a,1);--a;b.bd(...b.Qc)}}var K=[];function yb(a){var b=K[a];b.target.removeEventListener(b.bc,b.xc,b.cc);K.splice(a,1)}function L(a){if(!a.target)return-4;if(a.dc)a.xc=function(c){++ub;xb=a;wb();a.ec(c);wb();--ub},a.target.addEventListener(a.bc,a.xc,a.cc),K.push(a);else for(var b=0;b<K.length;++b)K[b].target==a.target&&K[b].bc==a.bc&&yb(b--);return 0}
function zb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var xb,Ab,Bb,Cb,Db,Eb,Fb,Gb,Hb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],M=a=>{a=2<a?a?F(x,a):"":a;return Hb[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},Ib=a=>0>Hb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},N,Jb=(a,b,c,d,e,g)=>{Ab||=O(256);a={target:M(a),bc:g,dc:d,ec:(f=event)=>{var m=f.target.id?f.target.id:"",n=Ab;G(zb(f.target),n+0,128);G(m,n+128,128);N.get(d)(e,n,b)&&f.preventDefault()},cc:c};return L(a)},Kb=(a,b,c,d,e,g)=>
{Bb||=O(176);a={target:M(a),bc:g,dc:d,ec:f=>{var m=Bb;B[m>>3]=f.timeStamp;var n=m>>2;y[n+2]=f.location;y[n+3]=f.ctrlKey;y[n+4]=f.shiftKey;y[n+5]=f.altKey;y[n+6]=f.metaKey;y[n+7]=f.repeat;y[n+8]=f.charCode;y[n+9]=f.keyCode;y[n+10]=f.which;G(f.key||"",m+44,32);G(f.code||"",m+76,32);G(f.char||"",m+108,32);G(f.locale||"",m+140,32);N.get(d)(e,m,b)&&f.preventDefault()},cc:c};return L(a)},Lb=(a,b,c)=>{B[a>>3]=b.timeStamp;a>>=2;y[a+2]=b.screenX;y[a+3]=b.screenY;y[a+4]=b.clientX;y[a+5]=b.clientY;y[a+6]=b.ctrlKey;
y[a+7]=b.shiftKey;y[a+8]=b.altKey;y[a+9]=b.metaKey;ra[2*a+20]=b.button;ra[2*a+21]=b.buttons;y[a+11]=b.movementX;y[a+12]=b.movementY;c=Ib(c);y[a+13]=b.clientX-(c.left|0);y[a+14]=b.clientY-(c.top|0)},Mb=(a,b,c,d,e,g)=>{Cb||=O(72);a=M(a);return L({target:a,oc:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,bc:g,dc:d,ec:(f=event)=>{Lb(Cb,f,a);N.get(d)(e,Cb,b)&&f.preventDefault()},cc:c})},Nb=(a,b,c,d,e)=>{Db||=O(260);return L({target:a,bc:e,dc:d,ec:(g=event)=>{var f=Db,m=document.pointerLockElement||
document.ic||document.uc||document.sc;y[f>>2]=!!m;var n=m?.id||"";G(zb(m),f+4,128);G(n,f+132,128);N.get(d)(20,f,b)&&g.preventDefault()},cc:c})},Ob=(a,b,c,d,e)=>L({target:a,bc:e,dc:d,ec:(g=event)=>{N.get(d)(38,0,b)&&g.preventDefault()},cc:c}),Pb=(a,b,c,d)=>{Eb||=O(36);a=M(a);return L({target:a,bc:"resize",dc:d,ec:(e=event)=>{if(e.target==a){var g=document.body;if(g){var f=Eb;y[f>>2]=0;y[f+4>>2]=g.clientWidth;y[f+8>>2]=g.clientHeight;y[f+12>>2]=innerWidth;y[f+16>>2]=innerHeight;y[f+20>>2]=outerWidth;
y[f+24>>2]=outerHeight;y[f+28>>2]=pageXOffset|0;y[f+32>>2]=pageYOffset|0;N.get(d)(10,f,b)&&e.preventDefault()}}},cc:c})},Qb=(a,b,c,d,e,g)=>{Fb||=O(1696);a=M(a);return L({target:a,oc:"touchstart"==g||"touchend"==g,bc:g,dc:d,ec:f=>{for(var m,n={},p=f.touches,r=0;r<p.length;++r)m=p[r],m.yc=m.zc=0,n[m.identifier]=m;for(r=0;r<f.changedTouches.length;++r)m=f.changedTouches[r],m.yc=1,n[m.identifier]=m;for(r=0;r<f.targetTouches.length;++r)n[f.targetTouches[r].identifier].zc=1;p=Fb;B[p>>3]=f.timeStamp;var t=
p>>2;y[t+3]=f.ctrlKey;y[t+4]=f.shiftKey;y[t+5]=f.altKey;y[t+6]=f.metaKey;t+=7;var P=Ib(a),Sb=0;for(r in n)if(m=n[r],y[t]=m.identifier,y[t+1]=m.screenX,y[t+2]=m.screenY,y[t+3]=m.clientX,y[t+4]=m.clientY,y[t+5]=m.pageX,y[t+6]=m.pageY,y[t+7]=m.yc,y[t+8]=m.zc,y[t+9]=m.clientX-(P.left|0),y[t+10]=m.clientY-(P.top|0),t+=13,31<++Sb)break;y[p+8>>2]=Sb;N.get(d)(e,p,b)&&f.preventDefault()},cc:c})},Rb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,
d),a.drawArraysInstanced=(c,d,e,g)=>b.drawArraysInstancedANGLE(c,d,e,g),a.drawElementsInstanced=(c,d,e,g,f)=>b.drawElementsInstancedANGLE(c,d,e,g,f))},Tb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Ub=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Vb=a=>
{a.Sc=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},Wb=a=>{a.Vc=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},Xb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Yb=1,Zb=[],Q=[],$b=[],ac=[],bc=[],R=[],cc=[],dc=[],S=[],ec={},fc=4,gc=a=>{for(var b=Yb++,c=a.length;c<b;c++)a[c]=null;return b},hc=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=T[c](),f=g&&gc(d);g?(g.name=f,d[f]=g):U||=1282;y[b+4*e>>2]=f}},jc=(a,b)=>{a.ic||(a.ic=a.getContext,a.getContext=function(d,e){e=a.ic(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.qc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
ic(c,b):0},ic=(a,b)=>{var c=gc(dc),d={handle:c,attributes:b,version:b.qc,kc:a};a.canvas&&(a.canvas.Oc=d);dc[c]=d;("undefined"==typeof b.wc||b.wc)&&kc(d);return c},lc=a=>{V=dc[a];h.pc=T=V?.kc;return!(a&&!T)},kc=a=>{a||=V;if(!a.Lc){a.Lc=!0;var b=a.kc;Rb(b);Tb(b);Ub(b);Vb(b);Wb(b);2<=a.version&&(b.vc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.vc)b.vc=b.getExtension("EXT_disjoint_timer_query");b.Mc=b.getExtension("WEBGL_multi_draw");Xb(b).forEach(c=>{c.includes("lose_context")||
c.includes("debug")||b.getExtension(c)})}},mc={},U,V,nc=(a,b,c,d,e,g)=>{a={target:M(a),bc:g,dc:d,ec:(f=event)=>{N.get(d)(e,0,b)&&f.preventDefault()},cc:c};L(a)},oc=(a,b,c,d)=>{Gb||=O(104);return L({target:a,oc:!0,bc:"wheel",dc:d,ec:(e=event)=>{var g=Gb;Lb(g,e,a);B[g+72>>3]=e.deltaX;B[g+80>>3]=e.deltaY;B[g+88>>3]=e.deltaZ;y[g+96>>2]=e.deltaMode;N.get(d)(9,g,b)&&e.preventDefault()},cc:c})},pc=["default","low-power","high-performance"],qc=[null,[],[]];
function rc(){var a=Xb(T);return a=a.concat(a.map(b=>"GL_"+b))}
var sc=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=T.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){U||=1282;return}c=rc().length;break;case 33307:case 33308:if(2>V.version){U||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=T.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":U||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:U||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)y[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){U||=1280;q(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:U||=1280;q(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}y[b>>2]=c}else U||=1281},tc=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},uc=a=>{var b=tc(a)+1,c=O(b);c&&G(a,c,b);return c},vc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),wc=[],xc=a=>{a-=5120;return 0==a?qa:1==a?x:2==a?ra:4==a?y:6==a?A:5==a||28922==a||28520==a||30779==a||30782==a?z:sa},W=a=>{var b=T.Ic;if(b){var c=b.jc[a];"number"==typeof c&&(b.jc[a]=c=T.getUniformLocation(b,b.Gc[a]+(0<c?`[${c}]`:"")));return c}U||=1282},X=[],yc=[],Ac=a=>{var b=tc(a)+
1,c=zc(b);G(a,c,b);return c};
h.requestFullscreen=function(a,b){function c(){fb=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=mb,lb&&d.requestPointerLock(),fb=!0,J?("undefined"!=typeof SDL&&(y[SDL.screen>>2]=z[SDL.screen>>2]|8388608),qb(h.canvas),pb()):qb(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),J?("undefined"!=typeof SDL&&(y[SDL.screen>>2]=z[SDL.screen>>
2]&-8388609),qb(h.canvas),pb()):qb(d));h.onFullScreen?.(fb);h.onFullscreen?.(fb)}lb=a;J=b;"undefined"==typeof lb&&(lb=!0);"undefined"==typeof J&&(J=!1);var d=h.canvas;kb||(kb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||
e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};h.requestAnimationFrame=Ta;h.setCanvasSize=function(a,b,c){qb(h.canvas,a,b);c||pb()};h.pauseMainLoop=eb;h.resumeMainLoop=function(){I++;var a=Ma,b=Na,c=Oa;Oa=null;cb(c,0,!1,Wa,!0);Va(a,b);H()};
h.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};h.createContext=function(a,b,c,d){if(b&&h.pc&&a==h.canvas)return h.pc;var e;if(b){var g={antialias:!1,alpha:!1,qc:"undefined"!=typeof WebGL2RenderingContext?2:1};if(d)for(var f in d)g[f]=d[f];if("undefined"!=typeof mc&&(e=jc(a,g)))var m=dc[e].kc}else m=a.getContext("2d");if(!m)return null;c&&(h.pc=m,b&&lc(e),h.cd=b,hb.forEach(n=>n()),ib());return m};
for(var T,Y=0;32>Y;++Y)wc.push(Array(Y));var Bc=new Float32Array(288);for(Y=0;288>Y;++Y)X[Y]=Bc.subarray(0,Y+1);var Cc=new Int32Array(288);for(Y=0;288>Y;++Y)yc[Y]=Cc.subarray(0,Y+1);
var Jc={da:function(){return 0},lb:function(){return 0},mb:function(){},db:function(a,b,c){a=new Date(1E3*(b+2097152>>>0<4194305-!!a?(a>>>0)+4294967296*b:NaN));y[c>>2]=a.getUTCSeconds();y[c+4>>2]=a.getUTCMinutes();y[c+8>>2]=a.getUTCHours();y[c+12>>2]=a.getUTCDate();y[c+16>>2]=a.getUTCMonth();y[c+20>>2]=a.getUTCFullYear()-1900;y[c+24>>2]=a.getUTCDay();y[c+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0},eb:function(a,b,c){a=new Date(1E3*(b+2097152>>>0<4194305-!!a?(a>>>0)+4294967296*
b:NaN));y[c>>2]=a.getSeconds();y[c+4>>2]=a.getMinutes();y[c+8>>2]=a.getHours();y[c+12>>2]=a.getDate();y[c+16>>2]=a.getMonth();y[c+20>>2]=a.getFullYear()-1900;y[c+24>>2]=a.getDay();y[c+28>>2]=(Ja(a.getFullYear())?Ka:La)[a.getMonth()]+a.getDate()-1|0;y[c+36>>2]=-(60*a.getTimezoneOffset());b=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();y[c+32>>2]=(b!=d&&a.getTimezoneOffset()==Math.min(d,b))|0},fb:function(a){var b=new Date(y[a+20>>2]+1900,
y[a+16>>2],y[a+12>>2],y[a+8>>2],y[a+4>>2],y[a>>2],0),c=y[a+32>>2],d=b.getTimezoneOffset(),e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),g=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),f=Math.min(g,e);0>c?y[a+32>>2]=Number(e!=g&&f==d):0<c!=(f==d)&&(e=Math.max(g,e),b.setTime(b.getTime()+6E4*((0<c?f:e)-d)));y[a+24>>2]=b.getDay();y[a+28>>2]=(Ja(b.getFullYear())?Ka:La)[b.getMonth()]+b.getDate()-1|0;y[a>>2]=b.getSeconds();y[a+4>>2]=b.getMinutes();y[a+8>>2]=b.getHours();y[a+12>>2]=b.getDate();
y[a+16>>2]=b.getMonth();y[a+20>>2]=b.getYear();a=b.getTime();a=isNaN(a)?-1:a/1E3;return Dc((E=a,1<=+Math.abs(E)?0<E?+Math.floor(E/4294967296)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)),a>>>0},gb:function(a){var b=new Date(Date.UTC(y[a+20>>2]+1900,y[a+16>>2],y[a+12>>2],y[a+8>>2],y[a+4>>2],y[a>>2],0));y[a+24>>2]=b.getUTCDay();y[a+28>>2]=(b.getTime()-Date.UTC(b.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;a=b.getTime()/1E3;return Dc((E=a,1<=+Math.abs(E)?0<E?+Math.floor(E/4294967296)>>>0:~~+Math.ceil((E-
+(~~E>>>0))/4294967296)>>>0:0)),a>>>0},jb:(a,b,c,d)=>{function e(p){return(p=p.toTimeString().match(/\(([A-Za-z ]+)\)$/))?p[1]:"GMT"}var g=(new Date).getFullYear(),f=new Date(g,0,1),m=new Date(g,6,1);g=f.getTimezoneOffset();var n=m.getTimezoneOffset();z[a>>2]=60*Math.max(g,n);y[b>>2]=Number(g!=n);a=e(f);b=e(m);n<g?(G(a,c,7),G(b,d,7)):(G(a,d,7),G(b,c,7))},j:()=>{oa("")},Ua:()=>{eb();Oa=null},ib:()=>Date.now(),O:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,na:(a,b,c)=>{a=M(a);if(!a)return-4;
a=Ib(a);B[b>>3]=a.width;B[c>>3]=a.height;return 0},Va:()=>performance.now(),_a:(a,b)=>{function c(d){N.get(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Qa:()=>{oa("OOM")},Q:(a,b,c,d)=>Jb(a,b,c,d,12,"blur"),M:(a,b,c)=>{a=M(a);if(!a)return-4;a.width=b;a.height=c;return 0},R:(a,b,c,d)=>Jb(a,b,c,d,13,"focus"),$:(a,b,c,d)=>Kb(a,b,c,d,2,"keydown"),Z:(a,b,c,d)=>Kb(a,b,c,d,1,"keypress"),_:(a,b,c,d)=>Kb(a,b,c,d,3,"keyup"),$a:(a,b,c)=>{a=N.get(a);cb(a,b,c)},x:(a,b,c,d)=>Mb(a,b,c,d,5,"mousedown"),
ia:(a,b,c,d)=>Mb(a,b,c,d,33,"mouseenter"),ga:(a,b,c,d)=>Mb(a,b,c,d,34,"mouseleave"),ja:(a,b,c,d)=>Mb(a,b,c,d,8,"mousemove"),ma:(a,b,c,d)=>Mb(a,b,c,d,6,"mouseup"),T:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.ic||document.body.uc||document.body.sc))return-1;a=M(a);if(!a)return-4;Nb(a,b,c,d,"mozpointerlockchange");Nb(a,b,c,d,"webkitpointerlockchange");Nb(a,b,c,d,"mspointerlockchange");return Nb(a,b,c,d,"pointerlockchange")},S:(a,b,c,d)=>{if(!document||
!(document.body.requestPointerLock||document.body.ic||document.body.uc||document.body.sc))return-1;a=M(a);if(!a)return-4;Ob(a,b,c,d,"mozpointerlockerror");Ob(a,b,c,d,"webkitpointerlockerror");Ob(a,b,c,d,"mspointerlockerror");return Ob(a,b,c,d,"pointerlockerror")},W:(a,b,c,d)=>Pb(a,b,c,d),U:(a,b,c,d)=>Qb(a,b,c,d,25,"touchcancel"),V:(a,b,c,d)=>Qb(a,b,c,d,23,"touchend"),X:(a,b,c,d)=>Qb(a,b,c,d,24,"touchmove"),Y:(a,b,c,d)=>Qb(a,b,c,d,22,"touchstart"),P:(a,b,c,d)=>{nc(a,b,c,d,31,"webglcontextlost");return 0},
N:(a,b,c,d)=>{nc(a,b,c,d,32,"webglcontextrestored");return 0},ba:(a,b,c,d)=>(a=M(a))?"undefined"!=typeof a.onwheel?oc(a,b,c,d):-1:-4,Ma:(a,b)=>{b>>=2;b={alpha:!!y[b],depth:!!y[b+1],stencil:!!y[b+2],antialias:!!y[b+3],premultipliedAlpha:!!y[b+4],preserveDrawingBuffer:!!y[b+5],powerPreference:pc[y[b+6]],failIfMajorPerformanceCaveat:!!y[b+7],qc:y[b+8],Wc:y[b+9],wc:y[b+10],Jc:y[b+11],Xc:y[b+12],Zc:y[b+13]};a=M(a);return!a||b.Jc?0:jc(a,b)},ta:(a,b)=>{a=dc[a];b=b?F(x,b):"";b.startsWith("GL_")&&(b=b.substr(3));
"ANGLE_instanced_arrays"==b&&Rb(T);"OES_vertex_array_object"==b&&Tb(T);"WEBGL_draw_buffers"==b&&Ub(T);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&Vb(T);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&Wb(T);"WEBGL_multi_draw"==b&&(T.Mc=T.getExtension("WEBGL_multi_draw"));return!!a.kc.getExtension(b)},Ia:a=>lc(a)?0:-5,ca:()=>52,kb:()=>52,hb:function(){return 70},L:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var f=z[b>>2],m=z[b+4>>2];b+=8;for(var n=0;n<m;n++){var p=x[f+n],r=qc[a];0===p||
10===p?((1===a?na:q)(F(r,0)),r.length=0):r.push(p)}e+=m}z[d>>2]=e;return 0},ha:a=>T.activeTexture(a),D:(a,b)=>{T.attachShader(Q[a],R[b])},d:(a,b)=>{35051==a?T.tc=b:35052==a&&(T.hc=b);T.bindBuffer(a,Zb[b])},r:(a,b,c)=>{T.bindBufferBase(a,b,Zb[c])},i:(a,b)=>{T.bindFramebuffer(a,$b[b])},Ga:(a,b)=>{T.bindRenderbuffer(a,ac[b])},q:(a,b)=>{T.bindSampler(a,S[b])},f:(a,b)=>{T.bindTexture(a,bc[b])},K:a=>{T.bindVertexArray(cc[a])},t:(a,b,c,d)=>T.blendColor(a,b,c,d),u:(a,b)=>T.blendEquationSeparate(a,b),v:(a,
b,c,d)=>T.blendFuncSeparate(a,b,c,d),vb:(a,b,c,d,e,g,f,m,n,p)=>T.blitFramebuffer(a,b,c,d,e,g,f,m,n,p),Ja:(a,b,c,d)=>{2<=V.version?c&&b?T.bufferData(a,x,d,c,b):T.bufferData(a,b,d):T.bufferData(a,c?x.subarray(c,c+b):b,d)},F:(a,b,c,d)=>{2<=V.version?c&&T.bufferSubData(a,b,x,d,c):T.bufferSubData(a,b,x.subarray(d,d+c))},ra:(a,b,c,d)=>T.clearBufferfi(a,b,c,d),y:(a,b,c)=>{T.clearBufferfv(a,b,A,c>>2)},qa:(a,b,c)=>{T.clearBufferiv(a,b,y,c>>2)},h:(a,b,c,d)=>{T.colorMask(!!a,!!b,!!c,!!d)},ob:a=>{T.compileShader(R[a])},
Aa:(a,b,c,d,e,g,f,m)=>{2<=V.version?T.hc||!f?T.compressedTexImage2D(a,b,c,d,e,g,f,m):T.compressedTexImage2D(a,b,c,d,e,g,x,m,f):T.compressedTexImage2D(a,b,c,d,e,g,m?x.subarray(m,m+f):null)},Ca:(a,b,c,d,e,g,f,m,n)=>{T.hc?T.compressedTexImage3D(a,b,c,d,e,g,f,m,n):T.compressedTexImage3D(a,b,c,d,e,g,f,x,n,m)},xa:()=>{var a=gc(Q),b=T.createProgram();b.name=a;b.nc=b.lc=b.mc=0;b.rc=1;Q[a]=b;return a},qb:a=>{var b=gc(R);R[b]=T.createShader(a);return b},s:a=>T.cullFace(a),rb:(a,b)=>{for(var c=0;c<a;c++){var d=
y[b+4*c>>2],e=Zb[d];e&&(T.deleteBuffer(e),e.name=0,Zb[d]=null,d==T.tc&&(T.tc=0),d==T.hc&&(T.hc=0))}},G:(a,b)=>{for(var c=0;c<a;++c){var d=y[b+4*c>>2],e=$b[d];e&&(T.deleteFramebuffer(e),e.name=0,$b[d]=null)}},o:a=>{if(a){var b=Q[a];b?(T.deleteProgram(b),b.name=0,Q[a]=null):U||=1281}},I:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=ac[d];e&&(T.deleteRenderbuffer(e),e.name=0,ac[d]=null)}},H:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=S[d];e&&(T.deleteSampler(e),e.name=0,S[d]=null)}},n:a=>{if(a){var b=
R[a];b?(T.deleteShader(b),R[a]=null):U||=1281}},J:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=bc[d];e&&(T.deleteTexture(e),e.name=0,bc[d]=null)}},La:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2];T.deleteVertexArray(cc[d]);cc[d]=null}},l:a=>T.depthFunc(a),m:a=>{T.depthMask(!!a)},b:a=>T.disable(a),ka:a=>{T.disableVertexAttribArray(a)},xb:(a,b,c)=>{T.drawArrays(a,b,c)},yb:(a,b,c,d)=>{T.drawArraysInstanced(a,b,c,d)},Ab:(a,b,c,d)=>{T.drawElements(a,b,c,d)},zb:(a,b,c,d,e)=>{T.drawElementsInstanced(a,
b,c,d,e)},e:a=>T.enable(a),Kb:a=>{T.enableVertexAttribArray(a)},la:a=>T.frontFace(a),Ka:(a,b)=>{hc(a,b,"createBuffer",Zb)},Ha:(a,b)=>{hc(a,b,"createRenderbuffer",ac)},ya:(a,b)=>{hc(a,b,"createSampler",S)},Ea:(a,b)=>{hc(a,b,"createTexture",bc)},Oa:(a,b)=>{hc(a,b,"createVertexArray",cc)},sa:(a,b)=>T.getAttribLocation(Q[a],b?F(x,b):""),a:(a,b)=>sc(a,b),va:(a,b,c,d)=>{a=T.getProgramInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?G(a,d,b):0;c&&(y[c>>2]=b)},C:(a,b,c)=>{if(c)if(a>=Yb)U||=1281;else if(a=
Q[a],35716==b)a=T.getProgramInfoLog(a),null===a&&(a="(unknown error)"),y[c>>2]=a.length+1;else if(35719==b){if(!a.nc)for(b=0;b<T.getProgramParameter(a,35718);++b)a.nc=Math.max(a.nc,T.getActiveUniform(a,b).name.length+1);y[c>>2]=a.nc}else if(35722==b){if(!a.lc)for(b=0;b<T.getProgramParameter(a,35721);++b)a.lc=Math.max(a.lc,T.getActiveAttrib(a,b).name.length+1);y[c>>2]=a.lc}else if(35381==b){if(!a.mc)for(b=0;b<T.getProgramParameter(a,35382);++b)a.mc=Math.max(a.mc,T.getActiveUniformBlockName(a,b).length+
1);y[c>>2]=a.mc}else y[c>>2]=T.getProgramParameter(a,b);else U||=1281},nb:(a,b,c,d)=>{a=T.getShaderInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?G(a,d,b):0;c&&(y[c>>2]=b)},fa:(a,b,c)=>{c?35716==b?(a=T.getShaderInfoLog(R[a]),null===a&&(a="(unknown error)"),y[c>>2]=a?a.length+1:0):35720==b?(a=T.getShaderSource(R[a]),y[c>>2]=a?a.length+1:0):y[c>>2]=T.getShaderParameter(R[a],b):U||=1281},Pa:(a,b)=>{if(2>V.version)return U||=1282,0;var c=ec[a];if(c)return 0>b||b>=c.length?(U||=1281,0):c[b];switch(a){case 7939:return c=
rc().map(uc),c=ec[a]=c,0>b||b>=c.length?(U||=1281,0):c[b];default:return U||=1280,0}},B:(a,b)=>{b=b?F(x,b):"";if(a=Q[a]){var c=a,d=c.jc,e=c.Hc,g;if(!d)for(c.jc=d={},c.Gc={},g=0;g<T.getProgramParameter(c,35718);++g){var f=T.getActiveUniform(c,g);var m=f.name;f=f.size;var n=vc(m);n=0<n?m.slice(0,n):m;var p=c.rc;c.rc+=f;e[n]=[f,p];for(m=0;m<f;++m)d[p]=m,c.Gc[p++]=n}c=a.jc;d=0;e=b;g=vc(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.Hc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||T.getUniformLocation(a,
b)))return d}else U||=1281;return-1},ub:(a,b,c)=>{for(var d=wc[b],e=0;e<b;e++)d[e]=y[c+4*e>>2];T.invalidateFramebuffer(a,d)},wa:a=>{a=Q[a];T.linkProgram(a);a.jc=0;a.Hc={}},Na:(a,b)=>{3317==a&&(fc=b);T.pixelStorei(a,b)},w:(a,b)=>T.polygonOffset(a,b),wb:a=>T.readBuffer(a),Fa:(a,b,c,d,e)=>T.renderbufferStorageMultisample(a,b,c,d,e),E:(a,b,c)=>{T.samplerParameterf(S[a],b,c)},c:(a,b,c)=>{T.samplerParameteri(S[a],b,c)},z:(a,b,c,d)=>T.scissor(a,b,c,d),pb:(a,b,c,d)=>{for(var e="",g=0;g<b;++g){var f=(f=z[c+
4*g>>2])?F(x,f,d?z[d+4*g>>2]:void 0):"";e+=f}T.shaderSource(R[a],e)},tb:(a,b,c)=>T.stencilFunc(a,b,c),pa:(a,b,c,d)=>T.stencilFuncSeparate(a,b,c,d),k:a=>T.stencilMask(a),sb:(a,b,c)=>T.stencilOp(a,b,c),oa:(a,b,c,d)=>T.stencilOpSeparate(a,b,c,d),za:(a,b,c,d,e,g,f,m,n)=>{if(2<=V.version)if(T.hc)T.texImage2D(a,b,c,d,e,g,f,m,n);else if(n){var p=xc(m);T.texImage2D(a,b,c,d,e,g,f,m,p,n>>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else T.texImage2D(a,b,c,d,e,g,f,m,null);else{p=T;var r=p.texImage2D;if(n){var t=xc(m);
var P=fc;P=e*(d*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[f-6402]||1)*t.BYTES_PER_ELEMENT+P-1&-P);n=t.subarray(n>>>31-Math.clz32(t.BYTES_PER_ELEMENT),n+P>>>31-Math.clz32(t.BYTES_PER_ELEMENT))}else n=null;r.call(p,a,b,c,d,e,g,f,m,n)}},Ba:(a,b,c,d,e,g,f,m,n,p)=>{if(T.hc)T.texImage3D(a,b,c,d,e,g,f,m,n,p);else if(p){var r=xc(n);T.texImage3D(a,b,c,d,e,g,f,m,n,r,p>>>31-Math.clz32(r.BYTES_PER_ELEMENT))}else T.texImage3D(a,b,c,d,e,g,f,m,n,null)},Da:(a,b,c)=>T.texParameteri(a,b,c),Jb:(a,
b,c)=>{if(2<=V.version)b&&T.uniform1fv(W(a),A,c>>2,b);else{if(288>=b)for(var d=X[b-1],e=0;e<b;++e)d[e]=A[c+4*e>>2];else d=A.subarray(c>>2,c+4*b>>2);T.uniform1fv(W(a),d)}},ua:(a,b)=>{T.uniform1i(W(a),b)},Fb:(a,b,c)=>{if(2<=V.version)b&&T.uniform1iv(W(a),y,c>>2,b);else{if(288>=b)for(var d=yc[b-1],e=0;e<b;++e)d[e]=y[c+4*e>>2];else d=y.subarray(c>>2,c+4*b>>2);T.uniform1iv(W(a),d)}},Ib:(a,b,c)=>{if(2<=V.version)b&&T.uniform2fv(W(a),A,c>>2,2*b);else{if(144>=b)for(var d=X[2*b-1],e=0;e<2*b;e+=2)d[e]=A[c+
4*e>>2],d[e+1]=A[c+(4*e+4)>>2];else d=A.subarray(c>>2,c+8*b>>2);T.uniform2fv(W(a),d)}},Eb:(a,b,c)=>{if(2<=V.version)b&&T.uniform2iv(W(a),y,c>>2,2*b);else{if(144>=b)for(var d=yc[2*b-1],e=0;e<2*b;e+=2)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2];else d=y.subarray(c>>2,c+8*b>>2);T.uniform2iv(W(a),d)}},Hb:(a,b,c)=>{if(2<=V.version)b&&T.uniform3fv(W(a),A,c>>2,3*b);else{if(96>=b)for(var d=X[3*b-1],e=0;e<3*b;e+=3)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>2];else d=A.subarray(c>>2,c+12*b>>2);
T.uniform3fv(W(a),d)}},Db:(a,b,c)=>{if(2<=V.version)b&&T.uniform3iv(W(a),y,c>>2,3*b);else{if(96>=b)for(var d=yc[3*b-1],e=0;e<3*b;e+=3)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2];else d=y.subarray(c>>2,c+12*b>>2);T.uniform3iv(W(a),d)}},Gb:(a,b,c)=>{if(2<=V.version)b&&T.uniform4fv(W(a),A,c>>2,4*b);else{if(72>=b){var d=X[4*b-1],e=A;c>>=2;for(var g=0;g<4*b;g+=4){var f=c+g;d[g]=e[f];d[g+1]=e[f+1];d[g+2]=e[f+2];d[g+3]=e[f+3]}}else d=A.subarray(c>>2,c+16*b>>2);T.uniform4fv(W(a),d)}},Cb:(a,
b,c)=>{if(2<=V.version)b&&T.uniform4iv(W(a),y,c>>2,4*b);else{if(72>=b)for(var d=yc[4*b-1],e=0;e<4*b;e+=4)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2],d[e+3]=y[c+(4*e+12)>>2];else d=y.subarray(c>>2,c+16*b>>2);T.uniform4iv(W(a),d)}},Bb:(a,b,c,d)=>{if(2<=V.version)b&&T.uniformMatrix4fv(W(a),!!c,A,d>>2,16*b);else{if(18>=b){var e=X[16*b-1],g=A;d>>=2;for(var f=0;f<16*b;f+=16){var m=d+f;e[f]=g[m];e[f+1]=g[m+1];e[f+2]=g[m+2];e[f+3]=g[m+3];e[f+4]=g[m+4];e[f+5]=g[m+5];e[f+6]=g[m+6];e[f+7]=
g[m+7];e[f+8]=g[m+8];e[f+9]=g[m+9];e[f+10]=g[m+10];e[f+11]=g[m+11];e[f+12]=g[m+12];e[f+13]=g[m+13];e[f+14]=g[m+14];e[f+15]=g[m+15]}}else e=A.subarray(d>>2,d+64*b>>2);T.uniformMatrix4fv(W(a),!!c,e)}},g:a=>{a=Q[a];T.useProgram(a);T.Ic=a},Lb:(a,b)=>{T.vertexAttribDivisor(a,b)},Mb:(a,b,c,d,e,g)=>{T.vertexAttribPointer(a,b,c,!!d,e,g)},A:(a,b,c,d)=>T.viewport(a,b,c,d),cb:function(){h.Ac=a=>{0!=Ec()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",h.Ac)},bb:function(){h.Fc=
a=>{const b=a.clipboardData.getData("text");tb(()=>{const c=Ac(b);Fc(c)})};window.addEventListener("paste",h.Fc)},ab:function(a){h.$c=[];a=a?F(x,a):"";a=document.getElementById(a);h.Bc=b=>{b.stopPropagation();b.preventDefault()};h.Cc=b=>{b.stopPropagation();b.preventDefault()};h.Dc=b=>{b.stopPropagation();b.preventDefault()};h.Ec=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;h.ad=c;Gc(c.length);for(let e=0;e<c.length;e++)tb(()=>{const g=Ac(c[e].name);Hc(e,g)});let d=0;b.shiftKey&&
(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Ic(b.clientX,b.clientY,d)};a.addEventListener("dragenter",h.Bc,!1);a.addEventListener("dragleave",h.Cc,!1);a.addEventListener("dragover",h.Dc,!1);a.addEventListener("drop",h.Ec,!1)},Xa:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Nb:function(a){a=a?F(x,a):"";h.fc=document.getElementById(a);h.fc||console.log("sokol_app.h: invalid target:"+a);h.fc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+
a)},Ta:function(){window.removeEventListener("beforeunload",h.Ac)},Sa:function(){window.removeEventListener("paste",h.Fc)},Ra:function(a){a=a?F(x,a):"";a=document.getElementById(a);a.removeEventListener("dragenter",h.Bc);a.removeEventListener("dragleave",h.Cc);a.removeEventListener("dragover",h.Dc);a.removeEventListener("drop",h.Ec)},p:function(){h.fc&&h.fc.requestPointerLock&&h.fc.requestPointerLock()},Za:function(a,b){if(h.fc){if(0===b)a="none";else switch(a){case 0:a="auto";break;case 1:a="default";
break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}h.fc.style.cursor=a}},Wa:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),g=e.createImageData(a,b);g.data.set(x.subarray(c,c+a*b*4));e.putImageData(g,0,0);a=document.createElement("link");
a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Ya:function(a){a=a?F(x,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},
ea:function(){return navigator.userAgent.includes("Macintosh")?1:0},aa:function(a,b){b=b?F(x,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z=function(){function a(c){Z=c.exports;pa=Z.Ob;c=pa.buffer;h.HEAP8=qa=new Int8Array(c);h.HEAP16=ra=new Int16Array(c);h.HEAPU8=x=new Uint8Array(c);h.HEAPU16=sa=new Uint16Array(c);h.HEAP32=y=new Int32Array(c);h.HEAPU32=z=new Uint32Array(c);h.HEAPF32=A=new Float32Array(c);h.HEAPF64=
B=new Float64Array(c);N=Z.ac;ua.unshift(Z.Pb);C--;h.monitorRunDependencies?.(C);0==C&&(null!==ya&&(clearInterval(ya),ya=null),za&&(c=za,za=null,c()));return Z}var b={a:Jc};C++;h.monitorRunDependencies?.(C);if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){return q(`Module.instantiateWasm callback failed with error: ${c}`),!1}Fa(b,function(c){a(c.instance)});return{}}(),Kc=h._main=(a,b)=>(Kc=h._main=Z.Qb)(a,b),Fc=h.__sapp_emsc_onpaste=a=>(Fc=h.__sapp_emsc_onpaste=Z.Rb)(a),Ec=h.__sapp_html5_get_ask_leave_site=
()=>(Ec=h.__sapp_html5_get_ask_leave_site=Z.Sb)(),Gc=h.__sapp_emsc_begin_drop=a=>(Gc=h.__sapp_emsc_begin_drop=Z.Tb)(a),Hc=h.__sapp_emsc_drop=(a,b)=>(Hc=h.__sapp_emsc_drop=Z.Ub)(a,b),Ic=h.__sapp_emsc_end_drop=(a,b,c)=>(Ic=h.__sapp_emsc_end_drop=Z.Vb)(a,b,c);h.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,g,f,m)=>(h.__sapp_emsc_invoke_fetch_cb=Z.Wb)(a,b,c,d,e,g,f,m);var O=a=>(O=Z.Xb)(a),Dc=a=>(Dc=Z.Yb)(a),rb=()=>(rb=Z.Zb)(),sb=a=>(sb=Z._b)(a),zc=a=>(zc=Z.$b)(a);h.___start_em_js=154736;h.___stop_em_js=160600;
var Lc;za=function Mc(){Lc||Nc();Lc||(za=Mc)};function Oc(a=[]){var b=Kc;a.unshift(ca);var c=a.length,d=zc(4*(c+1)),e=d;a.forEach(f=>{z[e>>2]=Ac(f);e+=4});z[e>>2]=0;try{var g=b(c,d);db(g)}catch(f){bb(f)}}
function Nc(){var a=ba;function b(){if(!Lc&&(Lc=!0,h.calledRun=!0,!v)){Ga(ua);Ga(va);if(h.onRuntimeInitialized)h.onRuntimeInitialized();Pc&&Oc(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();wa.unshift(c)}Ga(wa)}}if(!(0<C)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)xa();Ga(ta);0<C||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},
1)):b())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var Pc=!0;h.noInitialRun&&(Pc=!1);Nc();
